# .platform.app.yaml
name: client
type: "nodejs:14"
hooks:
  build: |
    yarn install
    yarn run build

dependencies:
  nodejs:
    yarn: "1.22.10"

# The size of the persistent disk of the application (in MB).
disk: 1024

relationships:
  cms: "cms:http"

# The configuration of the application when it is exposed to the web.
web:
  locations:
    "/":
      # The public directory of the application relative to its root.
      root: "build"
      index:
        - "index.html"
      scripts: false
      allow: true
      passthru: "/index.html"
